#!/bin/bash
# =================================================================================
# 服务器部署UX修复指南
# 用途: 在阿里云服务器上部署最新的UX修复
# 日期: 2026-01-13
# =================================================================================

echo "=========================================="
echo "🚀 服务器部署UX修复指南"
echo "=========================================="
echo ""

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# 服务器信息
SERVER_IP="172.16.0.196"
PROJECT_PATH="/opt/exam-analysis-helper"

echo "📋 部署信息:"
echo "   服务器IP: $SERVER_IP"
echo "   项目路径: $PROJECT_PATH"
echo ""

echo "=========================================="
echo "步骤 1: SSH 连接到服务器"
echo "=========================================="
echo ""
echo "请在本地终端执行以下命令:"
echo ""
echo -e "${GREEN}ssh root@$SERVER_IP${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 2: 进入项目目录"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 3: 备份当前版本（可选但推荐）"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}# 创建备份目录${NC}"
echo -e "${GREEN}mkdir -p ~/backups${NC}"
echo ""
echo -e "${GREEN}# 备份前端构建文件${NC}"
echo -e "${GREEN}tar -czf ~/backups/frontend-backup-\$(date +%Y%m%d-%H%M%S).tar.gz frontend/web/dist${NC}"
echo ""
echo -e "${GREEN}# 备份后端编译文件${NC}"
echo -e "${GREEN}tar -czf ~/backups/backend-backup-\$(date +%Y%m%d-%H%M%S).tar.gz backend/dist${NC}"
echo ""
echo -e "${YELLOW}💡 提示: 如果出现问题，可以用这些备份恢复${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 4: 拉取最新代码"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}git pull origin main${NC}"
echo ""
echo "预期输出:"
echo "   - 显示更新的文件列表"
echo "   - 包含 LowConfidenceConfirmDialog.tsx/css"
echo "   - 包含 FeedbackButton.css"
echo "   - 包含新增的文档和脚本"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 5: 检查更新的文件"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}git log --oneline -5${NC}"
echo ""
echo "应该看到最新的提交:"
echo "   修复UX问题: 对话框关闭、反馈按钮位置、手机端缓存、反馈查看工具"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 6: 安装/更新依赖（如果需要）"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}# 检查是否有新的依赖${NC}"
echo -e "${GREEN}cd frontend/web${NC}"
echo -e "${GREEN}npm install${NC}"
echo ""
echo -e "${GREEN}cd ../../backend${NC}"
echo -e "${GREEN}npm install${NC}"
echo ""
echo -e "${YELLOW}💡 提示: 本次更新没有新增依赖，这一步应该很快完成${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 7: 重新构建前端"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH/frontend/web${NC}"
echo -e "${GREEN}npm run build${NC}"
echo ""
echo "预期输出:"
echo "   - 显示构建进度"
echo "   - 最后显示 'build complete'"
echo "   - 生成 dist/ 目录"
echo ""
echo -e "${YELLOW}⏱️  预计耗时: 1-3分钟${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 8: 重新编译后端（如果需要）"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH/backend${NC}"
echo -e "${GREEN}npm run build${NC}"
echo ""
echo -e "${YELLOW}💡 提示: 本次更新主要是前端修改，后端编译应该很快${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 9: 复制数据文件到 dist 目录"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH/backend${NC}"
echo -e "${GREEN}mkdir -p dist/data${NC}"
echo -e "${GREEN}cp data/knowledge-points.json dist/data/${NC}"
echo ""
echo "验证文件是否存在:"
echo ""
echo -e "${GREEN}ls -lh dist/data/knowledge-points.json${NC}"
echo ""
echo "应该显示文件大小（约几KB）"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 10: 重启服务"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH${NC}"
echo -e "${GREEN}pm2 restart all${NC}"
echo ""
echo "或者分别重启:"
echo ""
echo -e "${GREEN}pm2 restart exam-helper-backend${NC}"
echo -e "${GREEN}pm2 restart exam-helper-frontend${NC}"
echo ""
echo "查看服务状态:"
echo ""
echo -e "${GREEN}pm2 status${NC}"
echo ""
echo "应该显示两个服务都是 'online' 状态"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 11: 检查服务日志"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}pm2 logs exam-helper-backend --lines 20${NC}"
echo ""
echo "检查是否有错误信息，应该看到:"
echo "   - 服务器启动成功"
echo "   - 监听端口 3002"
echo "   - 没有 ENOENT 错误"
echo ""
echo "按 Ctrl+C 退出日志查看"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 12: 测试 API 接口"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}curl http://localhost:3002/health${NC}"
echo ""
echo "应该返回:"
echo '   {"status":"ok","timestamp":"..."}'
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 13: 清除浏览器缓存（重要！）"
echo "=========================================="
echo ""
echo -e "${YELLOW}⚠️  重要: 用户需要清除浏览器缓存才能看到更新${NC}"
echo ""
echo "方法1: 强制刷新"
echo "   - 电脑端: Ctrl+Shift+R (Windows) 或 Cmd+Shift+R (Mac)"
echo "   - 手机端: 完全关闭浏览器应用，重新打开"
echo ""
echo "方法2: 清除缓存"
echo "   - 浏览器设置 → 清除浏览数据 → 缓存的图片和文件"
echo ""
echo "方法3: 使用无痕模式测试"
echo "   - 打开无痕/隐私浏览窗口"
echo "   - 访问网站测试新功能"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 14: 功能验证测试"
echo "=========================================="
echo ""
echo "请在浏览器中测试以下功能:"
echo ""
echo "✅ 测试1: 置信度对话框"
echo "   1. 上传一张模糊的试卷图片"
echo "   2. 等待低置信度对话框弹出"
echo "   3. 点击对话框外的灰色区域"
echo "   4. 对话框应该关闭"
echo ""
echo "✅ 测试2: 反馈按钮"
echo "   1. 在手机端打开网站"
echo "   2. 检查右下角反馈按钮位置"
echo "   3. 按钮不应该遮挡其他内容"
echo ""
echo "✅ 测试3: 访问口令"
echo "   1. 在手机端输入访问口令"
echo "   2. 完全关闭浏览器"
echo "   3. 重新打开，上传图片测试"
echo "   4. 应该不再提示"口令失效""
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "步骤 15: 查看用户反馈（可选）"
echo "=========================================="
echo ""
echo "在服务器上执行:"
echo ""
echo -e "${GREEN}cd $PROJECT_PATH${NC}"
echo -e "${GREEN}node 查看用户反馈.js${NC}"
echo ""
echo "这会显示用户提交的反馈信息"
echo ""
echo "导出为CSV:"
echo ""
echo -e "${GREEN}node 查看用户反馈.js --export${NC}"
echo ""
read -p "按回车键继续..."

echo ""
echo "=========================================="
echo "🎉 部署完成！"
echo "=========================================="
echo ""
echo "✅ 已完成的更新:"
echo "   1. 修复了置信度对话框无法关闭的问题"
echo "   2. 优化了反馈按钮的位置（手机端）"
echo "   3. 提供了手机端缓存问题的解决方案"
echo "   4. 添加了用户反馈查看工具"
echo ""
echo "📚 相关文档:"
echo "   - docs/UX优化说明_2026-01-13.md"
echo "   - docs/手机端访问口令问题解决方案.md"
echo "   - 测试UX修复.md"
echo ""
echo "🔧 常用命令:"
echo "   查看服务状态: pm2 status"
echo "   查看后端日志: pm2 logs exam-helper-backend"
echo "   重启服务: pm2 restart all"
echo "   查看反馈: node 查看用户反馈.js"
echo ""
echo "⚠️  注意事项:"
echo "   1. 用户需要清除浏览器缓存才能看到更新"
echo "   2. 建议通知用户更新内容"
echo "   3. 如有问题，可以用备份恢复"
echo ""
echo "=========================================="
echo ""
